---
# tasks file for jenkins

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: jenkins

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: jenkins

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: jenkins

- name: Ensure Jenkins is started and enabled on boot
  service: name={{ jenkins_service_name }} state=started enabled=yes
  tags: jenkins

- name: Ensure Jenkins is ready
  wait_for: port=8080 delay=5

- name: Install Jenkins CLI
  get_url: >
    url=http://localhost:8080/jnlpJars/jenkins-cli.jar
    dest={{ jenkins_home }}/jenkins-cli.jar
    owner=jenkins
    group=jenkins
    mode=0644
  tags: jenkins

- name: Update Jenkins plugin information
  get_url: >
    url=http://updates.jenkins-ci.org/update-center.json
    dest={{ jenkins_home }}/updates/default.json
    owner=jenkins
    group=jenkins
    mode=0644
    force=yes
  tags: jenkins

- name: Remove first line of plugin information file
  lineinfile: >
    dest={{ jenkins_home }}/updates/default.json
    regexp='^updateCenter.post\($'
    state=absent
  tags: jenkins

- name: Remove last line of plugin information file
  lineinfile: >
    dest={{ jenkins_home }}/updates/default.json
    regexp='^\);$'
    state=absent
  tags: jenkins

- name: Install and update Jenkins plugins
  command: java -jar {{ jenkins_home }}/jenkins-cli.jar -s http://localhost:8080 install-plugin {{ jenkins_plugins }}
  notify: restart jenkins
  tags: jenkins
