---
# tasks file for jenkins

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: jenkins

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: jenkins

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: jenkins

- name: Ensure Jenkins is started and enabled on boot
  service: name={{ jenkins_service_name }} state=started enabled=yes
  tags: jenkins
