---
# tasks file for jenkins (Ubuntu specific)

- name: Download Jenkins
  get_url: >
    url=http://pkg.jenkins-ci.org/debian-stable/binary/jenkins_{{ jenkins_version }}_all.deb
    dest=/root/
  tags: jenkins

- name: Install Jenkins
  apt: deb=/root/jenkins_{{ jenkins_version }}_all.deb state=present force=yes
  tags: jenkins
